language: python
python:
  - '3.8'
  - '3.7'
  - '3.6'

os: rhel
sudo: required
group: bluezone
addons:
  ssh_known_hosts:
    - 9.5.162.11
    - bejgsa.ibm.com

before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y sshpass
  - sudo apt-get install -y lftp=4.8.1-1ubuntu0.1 --allow-downgrades
  - python -m pip install --upgrade pip
  - pip install six==1.12.0 junit-xml pytest==5.3.0 openstacksdk pycodestyle pylint ansible==2.9.13 ansible-doc-extractor sphinx sphinx_rtd_theme
  - pip install ansible-lint "ansible>=2.9,<2.10"
  - ansible --version
  - if [[ "$TRAVIS_BRANCH" =~ "release" ]]  && [[ $TRAVIS_PYTHON_VERSION = 3.8 ]] ; then
      ansible-playbook .script/code-convert.yml;
    fi
  - cd docs
  - rm -rf source/modules/*
  - make
  - if [[ "$TRAVIS_BRANCH" = "update-gh-pages" ]] || [[ "$TRAVIS_BRANCH" =~ "release" ]] ; then
      if  [[ $TRAVIS_PYTHON_VERSION = 3.8 ]] ; then
        mkdir ../../../gh-pages;
        cp -R build/. ../../../gh-pages/;
      fi
    fi
  - rm -rf build
  - cd /home/travis/build/IBMi-Cloud
  - pwd
  - git clone https://github.com/ansible/ansible.git
  - cd ansible
  - git checkout stable-2.10
  - cp -r /home/travis/build/IBMi-Cloud/ansible-for-i-development/.script/tests/sanity/* test/sanity
  - cp -r /home/travis/build/IBMi-Cloud/ansible-for-i-development/plugins/modules/* lib/ansible/modules/
  - ls -l test/sanity/
  - ls -l test/sanity/code-smell
  - source ./hacking/env-setup
  - pip install -r ./requirements.txt
  - pip install -r ./test/lib/ansible_test/_data/requirements/units.txt
  - pip install -r ./test/lib/ansible_test/_data/requirements/sanity.ansible-doc.txt
  - pip install -r ./test/lib/ansible_test/_data/requirements/sanity.import.txt
  - pip install -r ./test/lib/ansible_test/_data/requirements/sanity.pep8.txt
  - pip install -r ./test/lib/ansible_test/_data/requirements/sanity.pylint.txt
  - pip install -r ./test/lib/ansible_test/_data/requirements/sanity.rstcheck.txt
  - pip install -r ./test/lib/ansible_test/_data/requirements/sanity.validate-modules.txt
  - pip install -r ./test/lib/ansible_test/_data/requirements/sanity.yamllint.txt
  - pip install flashtext
  - ansible-test --help
  - cd /home/travis/build/IBMi-Cloud/ansible-for-i-development

install:
  - ansible-galaxy collection build .
  - ansible-galaxy collection install *.gz

script:
  - pushd ~/.ansible/collections/ansible_collections/ibm/power_ibmi
  - ansible-test sanity --python $TRAVIS_PYTHON_VERSION
  - rm -rf /home/travis/build/IBMi-Cloud/ansible
  #- pip install ansible==2.9.13
  - cp /home/travis/build/IBMi-Cloud/ansible-for-i-development/ansible.cfg ~/.ansible/collections/ansible_collections/ibm/power_ibmi/
  - ls -al
  - ansible --version
  - ansible-lint -x comments-indentation --exclude playbooks

after_success:
  - echo $TRAVIS_BRANCH
  - cd /home/travis/build/IBMi-Cloud/ansible-for-i-development
  - if [[ "$TRAVIS_BRANCH" = "dev" ]] || [[ "$TRAVIS_BRANCH" =~ "release" ]] ; then
      if  [[ $TRAVIS_PYTHON_VERSION = 3.8 ]] ; then
        chmod 755 .script/publish-build.sh;
        .script/publish-build.sh;
      fi
    fi

  - if [[ "$TRAVIS_BRANCH" = "git-sync" ]] || [[ "$TRAVIS_BRANCH" =~ "release" ]] ; then
      if  [[ $TRAVIS_PYTHON_VERSION = 3.8 ]] ; then
        chmod 755 .script/push.sh;
        .script/push.sh;
      fi
    fi

  - if [[ "$TRAVIS_BRANCH" = "update-gh-pages" ]] || [[ "$TRAVIS_BRANCH" =~ "release" ]] ; then
      if  [[ $TRAVIS_PYTHON_VERSION = 3.8 ]] ; then
        chmod 755 .script/update-gh-pages.sh;
        .script/update-gh-pages.sh;
      fi
    fi

notifications:
  #slack:
    #on_failure: always
    #rooms:
      #- ibmi-cloud
