- name: Capture an image from an existing vm
  ibmi_powervc_os_server_capture:
    name: '{{image_name}}' 
    auth: 
      auth_url: https://{{ansible_ssh_host}}:5000/v3
      username: '{{ansible_ssh_user}}'      
      password: '{{ansible_ssh_pass}}'
      project_name: '{{project}}'
      project_domain_name: '{{project_domain}}'
      user_domain_name: '{{user_domain}}'
    verify: '{{verify_cert}}'
    server: '{{vm_name}}'
  register: image_info