---
# tasks file for compare_path
- name: compose same_name
  set_fact:
    same_name: false

- block:
    - name: Recursively compare the files' path between target server and repo server one by one
      include_tasks: compare_checksum.yml
      when: find_result_target_var.path | basename == find_result_repo_var.path | basename
      with_list: "{{ find_result_target.files }}"
      loop_control:
        loop_var: find_result_target_var

    - name: Set same_files to false if no file has the same name on target server
      set_fact:
        same_files: false
      when: same_name is false

  when: same_files is true
