---
# role for check_file
# This role will check the image files' checksum between target server and repository server, in order to determine if can skip the transfer or not
- name: compose same_files
  set_fact:
    same_files: true

- name: Recursively find files on target server
  find:
    paths: "{{ target_file_path }}"
    recurse: true
    get_checksum: true
  register: find_result_target

- name: Print find_result
  debug:
    var: find_result_target

- name: Recursively find files on repo server
  find:
    paths: "{{ repo_file_path }}"
    recurse: true
    get_checksum: true
  delegate_to: "{{ repo_server }}"
  register: find_result_repo

- name: Print find_result
  debug:
    var: find_result_repo

- name: Check if target server dir or repo server dir is empty
  set_fact:
    same_files: false
  when: find_result_repo.files == [] or find_result_target.files == []

- name: Recursively compare the files' checksum between target server and repo server
  include_tasks: compare_path.yml
  loop: "{{ find_result_repo.files }}"
  loop_control:
    loop_var: find_result_repo_var

- name: Print same_files
  debug:
    var: same_files
