---
# role for sync_apply_individual_ptfs
- name: initialize sync_list
  set_fact:
    sync_list: []
    coverletter_list: []

- name: compose sync list and coverletter_list
  set_fact:
    sync_list: "{{ sync_list|default([]) + [ not_loaded_list_var | combine( {'src': not_loaded_list_var.file_path} )] }}"
    coverletter_list: "{{ coverletter_list|default([]) + [ not_loaded_list_var | combine( {'src': '/qsys.lib/qgpl.lib/qapzcover.file/Q'
    + not_loaded_list_var.ptf_id + '.mbr'} )] }}"
  loop: "{{ not_loaded_list }}"
  loop_control:
    loop_var: not_loaded_list_var

- name: transfer ptf savfs to target ibm i system
  ibm.power_ibmi.ibmi_synchronize_files:
    dest: "{{ dest }}"
    src_list: "{{ sync_list }}"
  when: sync_list != []
  delegate_to: "{{ src_host }}"
  ignore_errors: true
  register: sync_result

- name: transfer ptfs' cover letter to target ibm i system
  ibm.power_ibmi.ibmi_synchronize_files:
    dest: "/qsys.lib/qgpl.lib/qapzcover.file"
    src_list: "{{ coverletter_list }}"
  when: coverletter_list != []
  delegate_to: "{{ src_host }}"
  ignore_errors: true
  register: sync_coverletter_result

- name: compose sync result list
  set_fact:
    sync_success_list: "{{ sync_result.success_list | default([]) }}"
    sync_fail_list: "{{ sync_result.fail_list | default([]) }}"
    sync_coverletter_success_list: "{{ sync_coverletter_result.success_list | default([]) }}"
    sync_coverletter_fail_list: "{{ sync_coverletter_result.fail_list | default([]) }}"

- name: Print the list of successful sync
  debug:
    var: sync_success_list

- name: Print the list of failed sync
  debug:
    var: sync_fail_list

- name: Print the list of successful coverletter sync
  debug:
    var: sync_coverletter_success_list

- name: Print the list of failed coverletter sync
  debug:
    var: sync_coverletter_fail_list

- name: Include load_apply_ptfs role to load and apply ptfs
  include_role:
    name: load_apply_ptfs
  vars:
    to_be_loaded_ptf_list: "{{ sync_success_list }}"
    remote_lib: "{{ (dest | basename | splitext)[0] }}"
    loaded_list: "{{ already_loaded_list }}"
  when: sync_success_list != [] or already_loaded_list != []
