---
# tasks file for check_ptfs_by_product
- fail:
    msg: "repository server is not provided, please provide the repository server."
  when: repo_server == "" or repo_server is undefined

- fail:
    msg: "product is not provided, please provide the product id."
  when: product == "" or product is undefined

- set_fact:
    ptf_status: []

- name: retrieve the PTF list by product from repository server
  ibm.power_ibmi.ibmi_fix_repo:
    action: "find"
    type: "single_ptf"
    parameters: 
      - { 'product': '{{ product }}' }
  delegate_to: "{{ repo_server }}"
  register: product_info

- name: got record failed from repository server
  set_fact:
    ptf_status: "{{ ptf_status|default([]) + [{ 'PRODUCT': prod.product, 'PRODUCT_STATUS': 'Record not found in repository DB' }] }}"
  when: product_info.get('fail_list')
  with_list: "{{ product_info.fail_list }}"
  loop_control:
    loop_var: prod

- name: compare the ptfs on target system
  include_tasks: compare_ptf.yml
  when: product_info.get('success_list')
