- name: find the line description name
  set_fact:
    find_lind: false

- name: find the line description name
  set_fact:
    lind: "{{ lind_line.split(' ')[1] }}"
    find_lind: true
  when: "'*LIN' in lind_line"

- name: display line description
  ibmi_cl_command:
    cmd: dsplind {{ lind }}
  register: lind_details
  when: find_lind == true 

- name: check if resource name exists
  set_fact:
    line_description: '{{ lind }}' 
  when: find_lind == true and resource_name in lind_details.stdout